packages:
  - examples/*
  - examples/*/apps/*
  - examples/*/bundle/*
  - examples/*/plugins/*
  - examples/*/shared
  - packages/*

allowBuilds:
  electron: true
  esbuild: true
  simple-git-hooks: true
