import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { loadWebBootGraph } from '@react-cordis/boot-config';
import { renderWebBootVirtualModule } from '@react-cordis/vite';

const directory = resolve(import.meta.dirname, '..');
const require = createRequire(import.meta.url);
for (const target of ['server', 'client']) {
  const graph = loadWebBootGraph(resolve(directory, `cordis.${target}.yml`));
  const source = renderWebBootVirtualModule(graph, name => Boolean(require.resolve(name)));
  writeFileSync(resolve(directory, `src/boot.${target}.generated.js`), `// Generated by pnpm generate.\n${source}`);
}
